development:
  adapter: postgresql
  database: pastie
  host: localhost
  username: tinypastie
  password: tinypastie
production:
  adapter: postgresql
  encoding: unicode
  database: tinypastie
  pool: 5
