development:
  adapter: mysql2
  database: toopaste
  host: <%= ENV["#{ENV['DB_PREFIX']}_PORT_3306_TCP_ADDR"] %>
  port: <%= ENV["#{ENV['DB_PREFIX']}_PORT_3306_TCP_PORT"] %>
  username: <%= ENV["#{ENV['DB_PREFIX']}_ENV_MYSQL_USER"] %>
  password: <%= ENV["#{ENV['DB_PREFIX']}_ENV_MYSQL_PASSWORD"] %>
